name: Hacker Bootstrap Shop
markdown: redcarpet
pygments: true

#Github Deployment
baseurl: /hackerbootshop
#Local Deployment
#baseurl: ""
paginate: 100
paginate_path: "page/:num"
show_drafts: false
permalink: none
