name: Tahoma Outdoor Gear
markdown: redcarpet
pygments: false

#Github Deployment
baseurl: ""
#Local Deployment
#baseurl: ""
paginate: 100
paginate_path: "page/:num"
show_drafts: false
permalink: none
